# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5a86b5e22880a9fca16da643e78b9b45fc58af4b83554e712e3522e530d635e00879d0717058cfebdaf0cb140bc8a1ea235014bb5226c4e366aeab43ac4bff

test:
  secret_key_base: e2ea8092b0fafaa11d0d375845cf317d4f126818e6d10cc5fc2b591633fcfb865b05847f6d0a00532e8a24c653f9fade98945dc5070563356755a4efc8ce12e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e2ea8092b0fafaa11d0d375845cf317d4f126818e6d10cc5fc2b591633fcfb865b05847f6d0a00532e8a24c653f9fade98945dc5070563356755a4efc8ce12e3
